version: '3'
volumes:
  mysql_data:
      driver: local
services:
  db:
      image: mysql:latest
      container_name: mysql_auth_server
      restart: always
      volumes:
        - ./mysql_data:/var/lib/mysql
        - ./mysqlconf:/etc/mysql/conf.d
      ports:
        - "6603:3306"  
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_USERNAME: root
        MYSQL_DATABASE: db_salam
        MYSQL_USER: moussaoui
        MYSQL_PASSWORD: (S=M=A=I=L)  
              
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin:latest  
    restart: always
    ports:
        - '6081:80'
    # environment:
        # PMA_HOST: mysql_saltjb
        # MYSQL_ROOT_PASSWORD: root 
        # MYSQL_USER: moussaoui
        # MYSQL_PASSWORD: (S=M=A=I=L)
        # UPLOAD_LIMIT: 300M
